on:
  push:
    branches: [ master ]

jobs:
  build-release:
    name: Build Release
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build:
          - linux
          - linux-musl
          - macos
          - windows
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2

      - name: Build archive
        shell: bash
        run: |
          mkdir -p test
          7z a test.zip test/
