on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose up
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: sudo docker-compose up -d
    - name: Check running containers
      run: ocker-compose ps -a
    - name: Check logs
      run: docker-compose logs app
    - name: Test with pytest
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: sudo docker-compose exec app pytest
